language: bash
sudo: required
services:
  - docker

env:
  global:
    - DOCKER_HOST=tcp://172.16.100.11:2375

before_install:
  # stupid way
  - DOCKER_HOST=tcp://127.0.0.1:2375 docker-compose up build -d
  - sudo bash -c 'echo DOCKER_OPTS="-H tcp://172.16.100.11:2375" > /etc/default/docker'
  - sudo service docker restart
  - netstat -an | grep LISTEN

install:
  - docker-compose build

script:
  - docker-compose up -d
  - sleep 5
  - curl http://localhost/api/apps
