language: bash
sudo: required
services:
  - docker
install:
  - ./script/deploy_via_docker.sh
script:
  - docker-compose exec mgmt apk add curl
  - docker-compose exec mgmt curl http://build:8080/builds
