language: bash
sudo: required
services:
  - docker

install:
  - docker-compose run mgmt bundle install --jobs 4 --without test --without development --without mysql
  - docker-compose run mgmt bundle exec rails db:migrate

script:
  - docker-compose up -d
  - curl http://localhost/api/apps
