language: bash
sudo: required
services:
  - docker

env:
  global:
    - DOCKER_HOST=tcp://172.16.100.11:2375

before_install:
  # stupid way
  - sudo bash -c 'echo DOCKER_OPTS="-H tcp://172.16.100.11" > /etc/default/docker'
  - netstat -an | grep LISTEN
  - sudo service docker restart

install:
  - docker-compose build

script:
  - docker-compose up -d
  - sleep 5
  - curl http://localhost/api/apps
