version: '2'

services:
  gateway:
    build: ./gateway
    networks:
      - front
    links:
      - mgmt
    ports:
      - '80:80'

  mgmt:
    build: ./mgmt
    networks:
      - front
      - back
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=not-a-secret

  build:
    build: ./build
    environment:
      - DOCKER_HOST=tcp://172.13.11.1
    networks:
      - back
      - allow_docker

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.11.11.0/24
        gateway: 172.11.11.1

  back:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.12.11.0/24
        gateway: 172.12.11.1

  allow_docker:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.13.11.0/24
        gateway: 172.13.11.1
