version: '2'

services:
  gateway:
    build: ./gateway
    links:
      - mgmt
    networks:
      - frontend
    ports:
      - '80:80'

  mgmt:
    build: ./mgmt
    networks:
      - frontend
      - backend
    links:
      - mgmt-db
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=TODO
      - DATABASE_URL=postgresql://postgres:postgres@mgmt-db

  mgmt-db:
    image: postgres
    networks:
      - backend
    volumes:
      - /var/lib/postgresql/data-mgmt:/var/lib/postgresql/data

  build:
    build: ./build
    networks:
      - backend

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.2.0/24
          gateway: 172.16.2.1
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.12.3.0/24
          gateway: 172.12.3.1
