version: '2'

services:
  gateway:
    build: ./gateway
    links:
      - mgmt
    networks:
      - frontend
    ports:
      - '80:80'

  mgmt:
    build: ./mgmt
    networks:
      - frontend
      - backend
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=TODO

  build:
    build: ./build
    networks:
      - backend

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.2.0/24
          gateway: 172.16.2.1
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.12.3.0/24
          gateway: 172.12.3.1
