#
#  localhost:8000    emu-server
#
version: '2'
services:
  gateway:
    build: ./gateway
    ports:
      - '80:80'
    links:
      - buildserver
      - mockup
      - mgmt

  # /*
  mockup:
    build: ./mockup
    links:
      - mockup-db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@mockup-db
  mockup-db:
    image: postgres
    volumes:
      - /data/mockup-db:/var/lib/postgresql/data

  # /mgmt/*
  mgmt:
    build: ./mgmt
    links:
      - buildserver
      - mgmt-db
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@mgmt-db
      - BUILDSERVER_URL=http://buildserver:8080
  mgmt-db:
    image: postgres
    volumes:
      - /data/mgmt-db:/var/lib/postgresql/data

  # /build/*
  buildserver:
    build: ./build
