#
#  localhost:8000    emu-server
#
version: '2'
services:
  public-gateway:
    build: ./public-gateway
    networks:
      - frontend
    ports:
      - '80:80'
    links:
      - mockup
      - mgmt

  gateway:
    build: ./gateway
    networks:
      - backend
    links:
      - buildserver

  # /*
  mockup:
    build: ./mockup
    networks:
      - frontend
    links:
      - mockup-db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@mockup-db
  mockup-db:
    image: postgres
    networks:
      - frontend
    volumes:
      - /data/mockup-db:/var/lib/postgresql/data

  # /mgmt/*
  mgmt:
    build: ./mgmt
    networks:
      - frontend
      - backend
    links:
      - mgmt-db
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@mgmt-db
  mgmt-db:
    image: postgres
    networks:
      - backend
    volumes:
      - /data/mgmt-db:/var/lib/postgresql/data

  # /build/*
  buildserver:
    build: ./build
    networks:
      - backend

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.2.0/24
          gateway: 172.16.2.1
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.12.3.0/24
          gateway: 172.12.3.1
